### ISSUE TITLE
yotpo_rich_snippets table was not created when upgrade from previous version.

### ISSUE THREAD

**Issue by altheaziyun** [YotpoLtd/magento2-module-yotpo-reviews#144]
Hi Yotpo,

The `yotpo_rich_snippets` table was not created when update from lower version, maybe you could check and create the table if the table do not exists.

**Comment by SlavicB** [comment]
Hi,

You've had an older version of the Yotpo extension and the upgrade did not create the table?
The table should've been created in an older version as well.
Would you kindly provide some additional details on how to replicate this issue?

Kindly,

**Comment by altheaziyun** [comment]
@SlavicB I use `composer update yotpo/module-review` to update from 2.2.8 to 2.4.5, after I run `php bin/magento setup:upgrade` the table was not created. I need to remove `Yotpo_Yotpo` row in `setup_module` table and run setup upgrade again to create the table. 

I also notice that yotpoBottomLine is showing twice in product info page after the update.

**Comment by Floddy** [comment]
Ran into this today;

The issue is that the DB table is added in the install script, and the install script was added after the module was initially released.

Since M2 _always_ stores module setup versions in the DB, Install scripts will only be ran at first install, but not if the install script is added in a later version. This is unless you remove it from setup_module ofc, but that is manual work, and could lead to issues if there's other upgrade scripts in the module that would now run twice.

Adding tables to a previously released module should be done in the upgrade script.

**Comment by jcdennen** [comment]
Just hit this issue with the Magento 2.3.5-p1 upgrade. anyone who had Yotpo installed prior to `v2.4` will run into a bug with the `UpgradeData` script. The script (as is) assumes the table exists, when it may not. Looks like there is a pending fix in #245
